### ISSUE TITLE
configuration doesn't work

### ISSUE THREAD

**Issue by lperdigaoTel** [jamesridgway/gradle-gitflow-plugin#16]
gitflow {
    // Customise template for unreleased version (uses freemarker)
    unreleasedVersionTemplate "${major}.${minor}.${patch}"
}

----------------------------
* What went wrong:
A problem occurred evaluating root project 'planet2-faults-adapter'.
> Could not get unknown property 'major' for object of type uk.co.jamesridgway.gradle.gitflow.plugin.GitFlowPluginExtension.

**Comment by jamesridgway** [comment]
What version of the plugin are you using?

**Comment by plutarchus45** [comment]
Hi @jamesridgway ,

I'm suffering from the same issue. We're considering using the plugin but need to change the unreleased format for compatibility considerations.

I tried with version 1.2.0, 1.3.0 and 1.4.0 of the plugin on a system with the following characteristics (MINGW64 environment for Git on Windows):
------------------------------------------------------------
Gradle 4.6
------------------------------------------------------------

Build time:   2018-02-28 13:36:36 UTC
Revision:     8fa6ce7945b640e6168488e4417f9bb96e4ab46c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_60 (Oracle Corporation 25.60-b23)
OS:           Windows 8.1 6.3 amd64

All result in the same "Could not get unknown property 'major' for object of type " error reported by @IperdigaoTel above.

Any thoughts/suggestions on fixing this would be nice. Thanks.

**Comment by jamesridgway** [comment]
Do either of you have a sample project you can share that recreates the issue?

**Comment by jamesridgway** [comment]
I've managed to reproduce this.

In 1.5.2 I have corrected the name of the property and updated the readme file. Note that the readme file now has the property defined using single-quotes (') - this is to avoid groovy variable substitution as the freemarker syntax is the same.

I still have a problem with the default value not actually being overridden. I should have some more time at the end of today to continue looking at this.

**Comment by jamesridgway** [comment]
This should now be fixed under 1.5.3

DSL based configuration is not loaded early enough to set the version such that it can be used in buildSrc stages of a gradle build.

As a result I have moved the configuration to be properties based and have added some detailed documentation on how you can configure this in the [configuration](https://github.com/jamesridgway/gradle-gitflow-plugin/wiki/Configuration) section of the [wiki](https://github.com/jamesridgway/gradle-gitflow-plugin/wiki).

**Comment by plutarchus45** [comment]
Setting the format for unreleased versions works for me now (1.5.3). Thanks @jamesridgway !
